preload = /home/yannis/Pictures/wallaper1.jpeg

wallpaper {
    monitor =  eDP-1
    path = /home/yannis/Pictures/wallaper1.jpeg
}

wallpaper {
    monitor =  HDMI-A-1
    path = /home/yannis/Pictures/wallaper1.jpeg
}

splash = false
