general {
    immediate_render = true
}

background {
    monitor =
    path = $HOME/Pictures/wallaper1.jpeg   # only png supported for now
    color = rgba(25, 20, 20, 1.0)

    # all these options are taken from hyprland, see https://wiki.hyprland.org/Configuring/Variables/#blur for explanations
    blur_passes = 0 # 0 disables blurring
    blur_size = 2
    noise = 0
    contrast = 0
    brightness = 0
    vibrancy = 0
    vibrancy_darkness = 0.0
}

input-field {
    monitor =
    size = 300, 30
    outline_thickness = 1
    dots_size = 0.25 # Scale of input-field height, 0.2 - 0.8
    dots_spacing = 0.55 # Scale of dots' absolute size, 0.0 - 1.0
    dots_center = true
    dots_rounding = -1

    # --- Couleurs & Contraste (Gris foncé) ---
    outer_color = rgba(242, 243, 244, 0.2)  # Bordure discrète
    inner_color = rgba(50, 50, 50, 0.85)    # Gris foncé (plus doux que le noir, très lisible)
    font_color = rgba(255, 255, 255, 1.0)    # Points de saisie en blanc pur
    dots_color = rgba(255, 255, 255, 1.0)    # Force le blanc opaque sur les points

    fade_on_empty = false
    placeholder_text = # Text rendered in the input box when it's empty.
    hide_input = false

    # --- Retours visuels lors des états ---
    check_color = rgba(204, 136, 34, 0.8)   # Bordure orange pendant la vérification
    fail_color = rgba(204, 34, 34, 0.8)     # Bordure rouge en cas d'erreur
    fail_text = $FAIL <b>($ATTEMPTS)</b>
    fail_transition = 300

    capslock_color = -1
    numlock_color = -1
    bothlock_color = -1
    invert_numlock = false
    swap_font_color = false

    position = 0, -468
    halign = center
    valign = center
}

label {
  monitor =
  text = cmd[update:1000] echo "$(~/.config/Scripts/song-status)"
  color = rgba(242, 243, 244, 0.75)
  font_size = 14
  font_family = SF Pro Text
  position = 20, 512
  halign = left
  valign = center
}

label {
  monitor =
  text = cmd[update:1000] echo "$(~/.config/Scripts/network-status)‎"
  color = rgba(242, 243, 244, 0.75)
  font_size = 16
  font_family = SF Pro Text
  position = -35, 512
  halign = right
  valign = center
}

label {
  monitor =
  text = cmd[update:1000] echo "$(~/.config/Scripts/battery-status)‎"
  color = rgba(242, 243, 244, 0.75)
  font_size = 19
  font_family = SF Pro Text
  position = -93, 512
  halign = right
  valign = center
}

label {
  monitor =
  text = cmd[update:1000] echo "$(~/.config/Scripts/layout-status)‎"
  color = rgba(242, 243, 244, 0.75)
  font_size = 15
  font_family = SF Pro Text
  position = -150, 512
  halign = right
  valign = center
}

label {
  monitor =
  text = cmd[update:1000] echo "$(date +"%A, %B %d")"
  color = rgba(242, 243, 244, 0.75)
  font_size = 20
  font_family = SF Pro Display Bold
  position = 0, 405
  halign = center
  valign = center
}

label {
  monitor =
  text = cmd[update:1000] echo "$(date +"%k:%M")"
  color = rgba(242, 243, 244, 0.75)
  font_size = 93
  font_family = SF Pro Display Bold
  position = 0, 310
  halign = center
  valign = center
}


label {
    monitor =
    text = Yannis Malgorn
    color = rgba(242, 243, 244, 0.75)
    font_size = 12
    font_family = SF Pro Display Bold
    position = 0, -407
    halign = center
    valign = center
}

label {
    monitor =
    text = Enter Password
    color = rgba(242, 243, 244, 0.75)
    font_size = 10
    font_family = SF Pro Display
    position = 0, -438
    halign = center
    valign = center
}

image {
    monitor =
    path = ~/Pictures/avatar.png
    border_color = 0xffdddddd
    border_size = 0
    size = 73
    rounding = -1
    rotate = 0
    reload_time = -1
    reload_cmd =
    position = 0, -353
    halign = center
    valign = center
}
